apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.16.6"
configMapGenerator:
- name: nfd-worker-conf
  behavior: replace
  files:
  - nfd-worker.conf
