apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-vpu-plugin
  labels:
    app: intel-vpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-vpu-plugin
  template:
    metadata:
      labels:
        app: intel-vpu-plugin
    spec:
      initContainers:
      - name: bslreset
        image: docker.io/openvisualcloud/vcaca-ubuntu1804-analytics-hddldaemon:latest
        command: [ "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/bin/bsl_reset" ]
        imagePullPolicy: IfNotPresent
        env:
        - name: LD_LIBRARY_PATH
          value: "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib"
        securityContext:
          privileged: true
      - name: clear
        image: clearlinux/os-core:latest
        command: [ "sh", "-c", "rm -f /var/tmp/hddl_*"]
        volumeMounts:
        - name: tmpfs
          mountPath: /var/tmp
      containers:
      - name: autoboot
        image: docker.io/openvisualcloud/vcaca-ubuntu1804-analytics-hddldaemon:latest
        command: [ "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/bin/autoboot" ]
        imagePullPolicy: IfNotPresent
        # environment: the container should set these by default. Also $PATH.
        env:
        - name: HDDL_INSTALL_DIR
          value: "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl"
        - name: LD_LIBRARY_PATH
          value: "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib"
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmpfs
          mountPath: /var/tmp
        - name: devfs
          mountPath: /dev/bus/usb
      - name: intel-vpu-plugin
        image: docker.io/intel/intel-vpu-plugin:devel
        # readinessProbe?
        args: [ "-debug", "1", "-autoboot-startup-delay", "20s" ]
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: devfs
          mountPath: /dev/bus/usb
        - name: sysfs1
          mountPath: /sys/bus/usb
        - name: sysfs2
          mountPath: /sys/devices
        - name: tmpfs
          mountPath: /var/tmp
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev/bus/usb
      - name: sysfs1
        hostPath:
          path: /sys/bus/usb
      - name: sysfs2
        hostPath:
          path: /sys/devices
      - name: tmpfs
        hostPath:
          path: /var/tmp
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-vpu-hddldaemon
  labels:
    app: intel-vpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-vpu-plugin
  template:
    metadata:
      labels:
        app: intel-vpu-plugin
    spec:
      containers:
      - name: hddldaemon
        image: docker.io/openvisualcloud/vcaca-ubuntu1804-analytics-hddldaemon:latest
        command: [ "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/bin/hddldaemon" ]
        imagePullPolicy: IfNotPresent
        env:
        - name: HDDL_INSTALL_DIR
          value: "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl"
        - name: LD_LIBRARY_PATH
          value: "/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib"
        # securitycontext: runAsGroup: users. the udev rules installed and daemons set the permissions
        resources:
          limits:
           vpu.intel.com/hddldaemon: '1'
