name: e2e-fpga
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
    branches:
      - main
      - 'release-*'

env:
  IMAGES: 'intel-fpga-plugin intel-fpga-initcontainer intel-fpga-admissionwebhook opae-nlb-demo'

jobs:
  e2e-fpga:
    name: e2e-fpga
    runs-on: [self-hosted, linux, x64, fpga]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: $IMAGES"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
