name: e2e
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches:
      - main
      - 'release-*'

permissions:
  contents: read

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: e2e-qat4
            runner: simics-spr
            images: intel-qat-plugin intel-qat-initcontainer openssl-qat-engine crypto-perf

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    env:
      TARGET_JOB: ${{ matrix.targetjob || matrix.name }}
      IMAGES: ${{ matrix.images }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: $IMAGES"
          echo "Target job: $TARGET_JOB"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
